### PR TITLE
feat: support safeheron wallet

### PR DESCRIPTION
**Pull request by beilunyang**
- 支持 Safeheron 浏览器插件钱包

### CODE REVIEW

**Comment by yutingzhao1991** [comment]
CI crashed, you need to update the icon's snapshot test cases.

**Comment by yutingzhao1991** [comment]
Additionally, you need to supplement test cases to ensure that the test coverage does not decline.

Thank you for your contribution.

**Comment by yutingzhao1991** [comment]
ant add a changelog with `pnpm changeset`

**Comment by beilunyang** [comment]
Resolved. Please code review again

**Review by gin-lsl — APPROVED** [review]

**Review by yutingzhao1991 — APPROVED** [review]

**Pull request merged**
