### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by aolyu1021**
Fix bad syntax 'viod' to 'void'

### CODE REVIEW

**Review by thinkasany — APPROVED** [review]

**Comment by thinkasany** [comment]
The English document can also be modified. @aolyu1021 
image

**Comment by aolyu1021** [comment]
> The English document can also be modified. @aolyu1021 image

Yes, do I need to submit a PR again?

**Comment by thinkasany** [comment]
> > The English document can also be modified. @aolyu1021 image
> 
> Yes, do I need to submit a PR again?

In this PR, just continue to commit.

**Comment by thinkasany** [comment]
Thanks for your contribution. You can reopen this PR, and then continue to submit modifications to another file above. We will merge your code after checking that there are no problems. @aolyu1021

**Pull request closed without merging**
